controller_manager:
  ros_parameters:
    update_rate: 100

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros_parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity